server:
  port: 8088
  servlet:
    context-path: /wechat.applet



spring:
  datasource:
    data-username: root
    data-password: root
    url: jdbc:mysql://localhost:3306/wechat_applet?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

mybatis:
  config-location: mybatis-config.xml
  mapper-locations: /mapper/**.xml
  type-aliases-package: com.entity







#spring:
#  profiles:
#    active: dev


# druid datasource configuration
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.url=jdbc:mysql://localhost:3306/wechat_applet?useUnicode=true&characterEncoding=utf-8&useSSL=false
#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource



# mybatis configuration
#mybatis.config-location=mybatis-config.xml
#mybatis.mapper-locations=/mapper/**.xml
#mybatis.type-aliases-package=com.entity











